### ISSUE TITLE
JWT decoding will accept any algorithm

### ISSUE THREAD

**Issue by karenetheridge** [jberger/Mojo-JWT#10]
My impression from reading the code is that any algorithm (other than 'none', if allow_none is not set) will be accepted for a submitted JWT to be decoded.  https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/ recommends that a library allow restricting the algorithm, so that a symmetric key algorithm cannot be selected.

This could be done by repurposing the 'algorithm' attribute, or perhaps adding a new attribute that took a list of acceptable algorithms that can be checked against 'alg' in the payload.

**Comment by jberger** [comment]
Thanks for the concern, however I did design the api to take care of that vulnerability. The method of restricting algos was a recommendation for retrofitting existing client libraries. Since my module was created after that vulnerability was already known I created my api differently. I separated out attributes for [public](https://metacpan.org/pod/Mojo::JWT#public) and [secret](https://metacpan.org/pod/Mojo::JWT#secret) keys such that mismatching symmetric/asymmetric algorithms will have no deleterious effect. I even then ran that notion past someone involved in that vuln to check what they thought and they agreed that it was a fine method for a new module (i wonder if I can find that conversation).

That said, I suspect that most modern uses of Mojo::JWT either use a peek callback or jwt_set anyway.

Thanks again and Cheers!

**Comment by karenetheridge** [comment]
I realized after I sent this that the server can always check the value of `alg` and refuse to process it if it is a value it does not like, i.e. restrict to only one preferred algorithm.

> That said, I suspect that most modern uses of Mojo::JWT either use a peek callback or jwt_set anyway.

I'm not quite sure what you mean by this?

**Comment by jberger** [comment]
I expect that most JWTs aren't statically pre-configured but the incoming JWT is checked against some list of possible keys. It would make no sense to use an incorrect asymmetric algorithm for a given key so even though you CAN let it pick the algorithm from the alg header field it still isn't useful if it is the wrong one for the pre-configured key. That's where the kid field comes from, you pre-configure lots of possible keys by key id (kid) and let it choose that way rather than `alg`. Manually you can do this via a "peek" callback, or `jwks` just automates that in a way that might even be available remotely as in openid-connect. For example, azure's openid-configuration is at https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration which points to the `jwk_uri` https://login.microsoftonline.com/common/discovery/v2.0/keys which can be loaded directly into Mojo::JWT. Then the appropriate key is used by kid. 

It still won't use an asymetric key as a symmetric secret however.
