### ISSUE TITLE
Regression decoding some jwts that are not encoded by Mojo::JWT

### ISSUE THREAD

**Issue by ugexe** [jberger/Mojo-JWT#5]
We have an application that generated tokens using `JSON::WebToken` and which does not set `typ => 'JWT'`. `Mojo::JWT` as of v0.06 now throws an exception when trying to decode these tokens.

I expect this would extend into decoding certain long-lived Mojo::JWT's generated tokens as well.

https://github.com/jberger/Mojo-JWT/commit/31d04204de078f2fadd4d97910dd72ae9dd4354b#diff-eecce135de825d0f32cca543e33c1079R36

Perhaps this is all expected, but I was not sure due to the versioning used.

**Comment by jberger** [comment]
I had had that restriction in a comment prior to that commit. I then suggested it be used as a mechanism by which to filter out the typ header from the resulting headers hash as implemented by that commit. I hadn't considered why that code was in a comment, which I imagine (now having consulted the rfc) that it was because I had realized that typ is only recommended and ignored.

So I can say, it was expected, but to expect it was the wrong thing. It is corrected now and has been sent to cpan as 0.07.

Thanks and sorry for any problems this caused.
